/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	DateTime: "String",
	RelEnum: "enum",
	TargetEnum: "enum",
	PageBodyNavigation:{
		items:{
			filter:{
				type:"CommonAFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"CommonASort",
				array:true,
				arrayRequired:false,
				required:true
			}
		}
	},
	CommonAFilter:{
		and:{
			type:"CommonAFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"CommonAFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	IDFilterComparison:{
		is:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		isNot:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		eq:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		neq:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		lt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		like:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		notLike:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		iLike:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		notILike:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		notIn:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	CommonASort:{
		field:{
			type:"CommonASortFields",
			array:false,
			arrayRequired:false,
			required:true
		},
		direction:{
			type:"SortDirection",
			array:false,
			arrayRequired:false,
			required:true
		},
		nulls:{
			type:"SortNulls",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CommonASortFields: "enum",
	SortDirection: "enum",
	SortNulls: "enum",
	ConnectionCursor: "String",
	Query:{
		page:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		pages:{
			paging:{
				type:"CursorPaging",
				array:false,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"pageFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"pageSort",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		head:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		heads:{
			paging:{
				type:"CursorPaging",
				array:false,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"headFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"headSort",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		meta:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		metas:{
			paging:{
				type:"CursorPaging",
				array:false,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"metaFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"metaSort",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		body:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		bodies:{
			paging:{
				type:"CursorPaging",
				array:false,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"bodyFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"bodySort",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		page_body_header:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		page_body_headers:{
			paging:{
				type:"CursorPaging",
				array:false,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"page_body_headerFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"page_body_headerSort",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		page_body_footer:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		page_body_footers:{
			paging:{
				type:"CursorPaging",
				array:false,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"page_body_footerFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"page_body_footerSort",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		main:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		mains:{
			paging:{
				type:"CursorPaging",
				array:false,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"mainFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"mainSort",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		pageBodyNavigation:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		pageBodyNavigations:{
			paging:{
				type:"CursorPaging",
				array:false,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"PageBodyNavigationFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"PageBodyNavigationSort",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		sidebar:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		sidebars:{
			paging:{
				type:"CursorPaging",
				array:false,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"sidebarFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"sidebarSort",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		commonA:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		commonAS:{
			paging:{
				type:"CursorPaging",
				array:false,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"CommonAFilter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sorting:{
				type:"CommonASort",
				array:true,
				arrayRequired:false,
				required:true
			}
		}
	},
	CursorPaging:{
		before:{
			type:"ConnectionCursor",
			array:false,
			arrayRequired:false,
			required:false
		},
		after:{
			type:"ConnectionCursor",
			array:false,
			arrayRequired:false,
			required:false
		},
		first:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		last:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	pageFilter:{
		and:{
			type:"pageFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"pageFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	pageSort:{
		field:{
			type:"pageSortFields",
			array:false,
			arrayRequired:false,
			required:true
		},
		direction:{
			type:"SortDirection",
			array:false,
			arrayRequired:false,
			required:true
		},
		nulls:{
			type:"SortNulls",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	pageSortFields: "enum",
	headFilter:{
		and:{
			type:"headFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"headFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"StringFieldComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	StringFieldComparison:{
		is:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		isNot:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		eq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		neq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		like:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		notLike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		iLike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		notILike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		notIn:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	headSort:{
		field:{
			type:"headSortFields",
			array:false,
			arrayRequired:false,
			required:true
		},
		direction:{
			type:"SortDirection",
			array:false,
			arrayRequired:false,
			required:true
		},
		nulls:{
			type:"SortNulls",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	headSortFields: "enum",
	metaFilter:{
		and:{
			type:"metaFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"metaFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	metaSort:{
		field:{
			type:"metaSortFields",
			array:false,
			arrayRequired:false,
			required:true
		},
		direction:{
			type:"SortDirection",
			array:false,
			arrayRequired:false,
			required:true
		},
		nulls:{
			type:"SortNulls",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	metaSortFields: "enum",
	bodyFilter:{
		and:{
			type:"bodyFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"bodyFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	bodySort:{
		field:{
			type:"bodySortFields",
			array:false,
			arrayRequired:false,
			required:true
		},
		direction:{
			type:"SortDirection",
			array:false,
			arrayRequired:false,
			required:true
		},
		nulls:{
			type:"SortNulls",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	bodySortFields: "enum",
	page_body_headerFilter:{
		and:{
			type:"page_body_headerFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"page_body_headerFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	page_body_headerSort:{
		field:{
			type:"page_body_headerSortFields",
			array:false,
			arrayRequired:false,
			required:true
		},
		direction:{
			type:"SortDirection",
			array:false,
			arrayRequired:false,
			required:true
		},
		nulls:{
			type:"SortNulls",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	page_body_headerSortFields: "enum",
	page_body_footerFilter:{
		and:{
			type:"page_body_footerFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"page_body_footerFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	page_body_footerSort:{
		field:{
			type:"page_body_footerSortFields",
			array:false,
			arrayRequired:false,
			required:true
		},
		direction:{
			type:"SortDirection",
			array:false,
			arrayRequired:false,
			required:true
		},
		nulls:{
			type:"SortNulls",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	page_body_footerSortFields: "enum",
	mainFilter:{
		and:{
			type:"mainFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"mainFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	mainSort:{
		field:{
			type:"mainSortFields",
			array:false,
			arrayRequired:false,
			required:true
		},
		direction:{
			type:"SortDirection",
			array:false,
			arrayRequired:false,
			required:true
		},
		nulls:{
			type:"SortNulls",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	mainSortFields: "enum",
	PageBodyNavigationFilter:{
		and:{
			type:"PageBodyNavigationFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"PageBodyNavigationFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PageBodyNavigationSort:{
		field:{
			type:"PageBodyNavigationSortFields",
			array:false,
			arrayRequired:false,
			required:true
		},
		direction:{
			type:"SortDirection",
			array:false,
			arrayRequired:false,
			required:true
		},
		nulls:{
			type:"SortNulls",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PageBodyNavigationSortFields: "enum",
	sidebarFilter:{
		and:{
			type:"sidebarFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"sidebarFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	sidebarSort:{
		field:{
			type:"sidebarSortFields",
			array:false,
			arrayRequired:false,
			required:true
		},
		direction:{
			type:"SortDirection",
			array:false,
			arrayRequired:false,
			required:true
		},
		nulls:{
			type:"SortNulls",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	sidebarSortFields: "enum",
	Mutation:{
		setHeadOnPage:{
			input:{
				type:"SetHeadOnPageInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		setBodyOnPage:{
			input:{
				type:"SetBodyOnPageInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOnePage:{
			input:{
				type:"CreateOnePageInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createManyPages:{
			input:{
				type:"CreateManyPagesInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOnePage:{
			input:{
				type:"UpdateOnePageInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateManyPages:{
			input:{
				type:"UpdateManyPagesInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOnePage:{
			input:{
				type:"DeleteOnePageInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteManyPages:{
			input:{
				type:"DeleteManyPagesInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		setMetaOnHead:{
			input:{
				type:"SetMetaOnHeadInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOneHead:{
			input:{
				type:"CreateOneHeadInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createManyHeads:{
			input:{
				type:"CreateManyHeadsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOneHead:{
			input:{
				type:"UpdateOneHeadInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateManyHeads:{
			input:{
				type:"UpdateManyHeadsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOneHead:{
			input:{
				type:"DeleteOneHeadInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteManyHeads:{
			input:{
				type:"DeleteManyHeadsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOneMeta:{
			input:{
				type:"CreateOneMetaInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createManyMetas:{
			input:{
				type:"CreateManyMetasInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOneMeta:{
			input:{
				type:"UpdateOneMetaInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateManyMetas:{
			input:{
				type:"UpdateManyMetasInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOneMeta:{
			input:{
				type:"DeleteOneMetaInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteManyMetas:{
			input:{
				type:"DeleteManyMetasInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		setHeaderOnBody:{
			input:{
				type:"SetHeaderOnBodyInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		setNavigationOnBody:{
			input:{
				type:"SetNavigationOnBodyInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		setMainOnBody:{
			input:{
				type:"SetMainOnBodyInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		setSidebarOnBody:{
			input:{
				type:"SetSidebarOnBodyInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		setFooterOnBody:{
			input:{
				type:"SetFooterOnBodyInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOneBody:{
			input:{
				type:"CreateOneBodyInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createManyBodies:{
			input:{
				type:"CreateManyBodiesInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOneBody:{
			input:{
				type:"UpdateOneBodyInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateManyBodies:{
			input:{
				type:"UpdateManyBodiesInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOneBody:{
			input:{
				type:"DeleteOneBodyInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteManyBodies:{
			input:{
				type:"DeleteManyBodiesInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOnePage_body_header:{
			input:{
				type:"CreateOnePage_body_headerInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createManyPage_body_headers:{
			input:{
				type:"CreateManyPage_body_headersInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOnePage_body_header:{
			input:{
				type:"UpdateOnePage_body_headerInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateManyPage_body_headers:{
			input:{
				type:"UpdateManyPage_body_headersInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOnePage_body_header:{
			input:{
				type:"DeleteOnePage_body_headerInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteManyPage_body_headers:{
			input:{
				type:"DeleteManyPage_body_headersInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOnePage_body_footer:{
			input:{
				type:"CreateOnePage_body_footerInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createManyPage_body_footers:{
			input:{
				type:"CreateManyPage_body_footersInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOnePage_body_footer:{
			input:{
				type:"UpdateOnePage_body_footerInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateManyPage_body_footers:{
			input:{
				type:"UpdateManyPage_body_footersInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOnePage_body_footer:{
			input:{
				type:"DeleteOnePage_body_footerInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteManyPage_body_footers:{
			input:{
				type:"DeleteManyPage_body_footersInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOneMain:{
			input:{
				type:"CreateOneMainInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createManyMains:{
			input:{
				type:"CreateManyMainsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOneMain:{
			input:{
				type:"UpdateOneMainInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateManyMains:{
			input:{
				type:"UpdateManyMainsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOneMain:{
			input:{
				type:"DeleteOneMainInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteManyMains:{
			input:{
				type:"DeleteManyMainsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		addItemsToPageBodyNavigation:{
			input:{
				type:"AddItemsToPageBodyNavigationInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		setItemsOnPageBodyNavigation:{
			input:{
				type:"SetItemsOnPageBodyNavigationInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOnePageBodyNavigation:{
			input:{
				type:"CreateOnePageBodyNavigationInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createManyPageBodyNavigations:{
			input:{
				type:"CreateManyPageBodyNavigationsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOnePageBodyNavigation:{
			input:{
				type:"UpdateOnePageBodyNavigationInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateManyPageBodyNavigations:{
			input:{
				type:"UpdateManyPageBodyNavigationsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOnePageBodyNavigation:{
			input:{
				type:"DeleteOnePageBodyNavigationInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteManyPageBodyNavigations:{
			input:{
				type:"DeleteManyPageBodyNavigationsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOneSidebar:{
			input:{
				type:"CreateOneSidebarInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createManySidebars:{
			input:{
				type:"CreateManySidebarsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOneSidebar:{
			input:{
				type:"UpdateOneSidebarInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateManySidebars:{
			input:{
				type:"UpdateManySidebarsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOneSidebar:{
			input:{
				type:"DeleteOneSidebarInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteManySidebars:{
			input:{
				type:"DeleteManySidebarsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOneCommonA:{
			input:{
				type:"CreateOneCommonAInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createManyCommonAS:{
			input:{
				type:"CreateManyCommonASInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOneCommonA:{
			input:{
				type:"UpdateOneCommonAInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateManyCommonAS:{
			input:{
				type:"UpdateManyCommonASInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOneCommonA:{
			input:{
				type:"DeleteOneCommonAInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteManyCommonAS:{
			input:{
				type:"DeleteManyCommonASInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	SetHeadOnPageInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		relationId:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	SetBodyOnPageInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		relationId:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateOnePageInput:{
		page:{
			type:"CreatePage",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreatePage:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lang:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateManyPagesInput:{
		pages:{
			type:"CreatePage",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	UpdateOnePageInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdatePage",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdatePage:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lang:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateManyPagesInput:{
		filter:{
			type:"pageUpdateFilter",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdatePage",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	pageUpdateFilter:{
		and:{
			type:"pageUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"pageUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DeleteOnePageInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	DeleteManyPagesInput:{
		filter:{
			type:"pageDeleteFilter",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	pageDeleteFilter:{
		and:{
			type:"pageDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"pageDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SetMetaOnHeadInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		relationId:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateOneHeadInput:{
		head:{
			type:"CreateHead",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateHead:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateManyHeadsInput:{
		heads:{
			type:"CreateHead",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	UpdateOneHeadInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateHead",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdateHead:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateManyHeadsInput:{
		filter:{
			type:"headUpdateFilter",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateHead",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	headUpdateFilter:{
		and:{
			type:"headUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"headUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"StringFieldComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DeleteOneHeadInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	DeleteManyHeadsInput:{
		filter:{
			type:"headDeleteFilter",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	headDeleteFilter:{
		and:{
			type:"headDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"headDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"StringFieldComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateOneMetaInput:{
		meta:{
			type:"CreateMeta",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateMeta:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		charset:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		noindex:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		nofollow:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		viewport:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateManyMetasInput:{
		metas:{
			type:"CreateMeta",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	UpdateOneMetaInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateMeta",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdateMeta:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		charset:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		noindex:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		nofollow:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		viewport:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateManyMetasInput:{
		filter:{
			type:"metaUpdateFilter",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateMeta",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	metaUpdateFilter:{
		and:{
			type:"metaUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"metaUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DeleteOneMetaInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	DeleteManyMetasInput:{
		filter:{
			type:"metaDeleteFilter",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	metaDeleteFilter:{
		and:{
			type:"metaDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"metaDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SetHeaderOnBodyInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		relationId:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	SetNavigationOnBodyInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		relationId:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	SetMainOnBodyInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		relationId:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	SetSidebarOnBodyInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		relationId:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	SetFooterOnBodyInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		relationId:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateOneBodyInput:{
		body:{
			type:"CreateBody",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateBody:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateManyBodiesInput:{
		bodies:{
			type:"CreateBody",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	UpdateOneBodyInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateBody",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdateBody:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateManyBodiesInput:{
		filter:{
			type:"bodyUpdateFilter",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateBody",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	bodyUpdateFilter:{
		and:{
			type:"bodyUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"bodyUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DeleteOneBodyInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	DeleteManyBodiesInput:{
		filter:{
			type:"bodyDeleteFilter",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	bodyDeleteFilter:{
		and:{
			type:"bodyDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"bodyDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateOnePage_body_headerInput:{
		page_body_header:{
			type:"CreatePage_body_header",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreatePage_body_header:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateManyPage_body_headersInput:{
		page_body_headers:{
			type:"CreatePage_body_header",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	UpdateOnePage_body_headerInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdatePage_body_header",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdatePage_body_header:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateManyPage_body_headersInput:{
		filter:{
			type:"page_body_headerUpdateFilter",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdatePage_body_header",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	page_body_headerUpdateFilter:{
		and:{
			type:"page_body_headerUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"page_body_headerUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DeleteOnePage_body_headerInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	DeleteManyPage_body_headersInput:{
		filter:{
			type:"page_body_headerDeleteFilter",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	page_body_headerDeleteFilter:{
		and:{
			type:"page_body_headerDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"page_body_headerDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateOnePage_body_footerInput:{
		page_body_footer:{
			type:"CreatePage_body_footer",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreatePage_body_footer:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateManyPage_body_footersInput:{
		page_body_footers:{
			type:"CreatePage_body_footer",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	UpdateOnePage_body_footerInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdatePage_body_footer",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdatePage_body_footer:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateManyPage_body_footersInput:{
		filter:{
			type:"page_body_footerUpdateFilter",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdatePage_body_footer",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	page_body_footerUpdateFilter:{
		and:{
			type:"page_body_footerUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"page_body_footerUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DeleteOnePage_body_footerInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	DeleteManyPage_body_footersInput:{
		filter:{
			type:"page_body_footerDeleteFilter",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	page_body_footerDeleteFilter:{
		and:{
			type:"page_body_footerDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"page_body_footerDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateOneMainInput:{
		main:{
			type:"CreateMain",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateMain:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateManyMainsInput:{
		mains:{
			type:"CreateMain",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	UpdateOneMainInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateMain",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdateMain:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateManyMainsInput:{
		filter:{
			type:"mainUpdateFilter",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateMain",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	mainUpdateFilter:{
		and:{
			type:"mainUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"mainUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DeleteOneMainInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	DeleteManyMainsInput:{
		filter:{
			type:"mainDeleteFilter",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	mainDeleteFilter:{
		and:{
			type:"mainDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"mainDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	AddItemsToPageBodyNavigationInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		relationIds:{
			type:"ID",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	SetItemsOnPageBodyNavigationInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		relationIds:{
			type:"ID",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	CreateOnePageBodyNavigationInput:{
		pageBodyNavigation:{
			type:"CreatePageBodyNavigation",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreatePageBodyNavigation:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateManyPageBodyNavigationsInput:{
		pageBodyNavigations:{
			type:"CreatePageBodyNavigation",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	UpdateOnePageBodyNavigationInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdatePageBodyNavigation",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdatePageBodyNavigation:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateManyPageBodyNavigationsInput:{
		filter:{
			type:"PageBodyNavigationUpdateFilter",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdatePageBodyNavigation",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	PageBodyNavigationUpdateFilter:{
		and:{
			type:"PageBodyNavigationUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"PageBodyNavigationUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DeleteOnePageBodyNavigationInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	DeleteManyPageBodyNavigationsInput:{
		filter:{
			type:"PageBodyNavigationDeleteFilter",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	PageBodyNavigationDeleteFilter:{
		and:{
			type:"PageBodyNavigationDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"PageBodyNavigationDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateOneSidebarInput:{
		sidebar:{
			type:"CreateSidebar",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateSidebar:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateManySidebarsInput:{
		sidebars:{
			type:"CreateSidebar",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	UpdateOneSidebarInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateSidebar",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdateSidebar:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateManySidebarsInput:{
		filter:{
			type:"sidebarUpdateFilter",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateSidebar",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	sidebarUpdateFilter:{
		and:{
			type:"sidebarUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"sidebarUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DeleteOneSidebarInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	DeleteManySidebarsInput:{
		filter:{
			type:"sidebarDeleteFilter",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	sidebarDeleteFilter:{
		and:{
			type:"sidebarDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"sidebarDeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateOneCommonAInput:{
		commonA:{
			type:"CreateCommonA",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CreateCommonA:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		href:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		rel:{
			type:"RelEnum",
			array:false,
			arrayRequired:false,
			required:false
		},
		target:{
			type:"TargetEnum",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateManyCommonASInput:{
		commonAS:{
			type:"CreateCommonA",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	UpdateOneCommonAInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateCommonA",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdateCommonA:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		created:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		href:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		rel:{
			type:"RelEnum",
			array:false,
			arrayRequired:false,
			required:false
		},
		target:{
			type:"TargetEnum",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UpdateManyCommonASInput:{
		filter:{
			type:"CommonAUpdateFilter",
			array:false,
			arrayRequired:false,
			required:true
		},
		update:{
			type:"UpdateCommonA",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CommonAUpdateFilter:{
		and:{
			type:"CommonAUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"CommonAUpdateFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DeleteOneCommonAInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	DeleteManyCommonASInput:{
		filter:{
			type:"CommonADeleteFilter",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CommonADeleteFilter:{
		and:{
			type:"CommonADeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		or:{
			type:"CommonADeleteFilter",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilterComparison",
			array:false,
			arrayRequired:false,
			required:false
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	User:{
		id:"Float",
		provider:"String",
		providerId:"String",
		username:"String",
		name:"String",
		created_at:"DateTime",
		updated_at:"DateTime"
	},
	meta:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		charset:"String",
		description:"String",
		noindex:"Boolean",
		nofollow:"Boolean",
		viewport:"String"
	},
	head:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String",
		meta:"meta"
	},
	page_body_header:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		type:"String"
	},
	CommonA:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		href:"String",
		rel:"RelEnum",
		target:"TargetEnum"
	},
	PageBodyNavigation:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String",
		items:"CommonA"
	},
	sidebar:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String"
	},
	page_body_footer:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		type:"String"
	},
	main:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String"
	},
	body:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		header:"HeaderUnion",
		navigation:"PageBodyNavigation",
		main:"main",
		sidebar:"sidebar",
		footer:"FooterUnion"
	},
	HeaderUnion:{
		"...on page_body_header_curved":"page_body_header_curved",
		"...on page_body_header_skewed":"page_body_header_skewed"
	},
	page_body_header_curved:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String",
		subTitle:"String"
	},
	page_body_header_skewed:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String",
		subTitle:"String"
	},
	FooterUnion:{
		"...on page_body_footer_extended":"page_body_footer_extended",
		"...on page_body_footer_simple":"page_body_footer_simple"
	},
	page_body_footer_extended:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String",
		subTitle:"String",
		copyright:"String"
	},
	page_body_footer_simple:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String",
		subTitle:"String",
		copyright:"String"
	},
	page:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		lang:"String",
		head:"head",
		body:"body"
	},
	DeleteManyResponse:{
		deletedCount:"Int"
	},
	PageDeleteResponse:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		lang:"String"
	},
	UpdateManyResponse:{
		updatedCount:"Int"
	},
	pageEdge:{
		node:"page",
		cursor:"ConnectionCursor"
	},
	PageInfo:{
		hasNextPage:"Boolean",
		hasPreviousPage:"Boolean",
		startCursor:"ConnectionCursor",
		endCursor:"ConnectionCursor"
	},
	PageConnection:{
		pageInfo:"PageInfo",
		edges:"pageEdge"
	},
	pageAggregateGroupBy:{
		id:"ID"
	},
	pageCountAggregate:{
		id:"Int"
	},
	pageSumAggregate:{
		id:"Float"
	},
	pageAvgAggregate:{
		id:"Float"
	},
	pageMinAggregate:{
		id:"ID"
	},
	pageMaxAggregate:{
		id:"ID"
	},
	HeadDeleteResponse:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String"
	},
	headEdge:{
		node:"head",
		cursor:"ConnectionCursor"
	},
	HeadConnection:{
		pageInfo:"PageInfo",
		edges:"headEdge"
	},
	headAggregateGroupBy:{
		id:"ID",
		title:"String"
	},
	headCountAggregate:{
		id:"Int",
		title:"Int"
	},
	headSumAggregate:{
		id:"Float"
	},
	headAvgAggregate:{
		id:"Float"
	},
	headMinAggregate:{
		id:"ID",
		title:"String"
	},
	headMaxAggregate:{
		id:"ID",
		title:"String"
	},
	MetaDeleteResponse:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		charset:"String",
		description:"String",
		noindex:"Boolean",
		nofollow:"Boolean",
		viewport:"String"
	},
	metaEdge:{
		node:"meta",
		cursor:"ConnectionCursor"
	},
	MetaConnection:{
		pageInfo:"PageInfo",
		edges:"metaEdge"
	},
	metaAggregateGroupBy:{
		id:"ID"
	},
	metaCountAggregate:{
		id:"Int"
	},
	metaSumAggregate:{
		id:"Float"
	},
	metaAvgAggregate:{
		id:"Float"
	},
	metaMinAggregate:{
		id:"ID"
	},
	metaMaxAggregate:{
		id:"ID"
	},
	BodyDeleteResponse:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime"
	},
	bodyEdge:{
		node:"body",
		cursor:"ConnectionCursor"
	},
	BodyConnection:{
		pageInfo:"PageInfo",
		edges:"bodyEdge"
	},
	bodyAggregateGroupBy:{
		id:"ID"
	},
	bodyCountAggregate:{
		id:"Int"
	},
	bodySumAggregate:{
		id:"Float"
	},
	bodyAvgAggregate:{
		id:"Float"
	},
	bodyMinAggregate:{
		id:"ID"
	},
	bodyMaxAggregate:{
		id:"ID"
	},
	Page_body_headerDeleteResponse:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		type:"String"
	},
	page_body_headerEdge:{
		node:"page_body_header",
		cursor:"ConnectionCursor"
	},
	Page_body_headerConnection:{
		pageInfo:"PageInfo",
		edges:"page_body_headerEdge"
	},
	page_body_headerAggregateGroupBy:{
		id:"ID"
	},
	page_body_headerCountAggregate:{
		id:"Int"
	},
	page_body_headerSumAggregate:{
		id:"Float"
	},
	page_body_headerAvgAggregate:{
		id:"Float"
	},
	page_body_headerMinAggregate:{
		id:"ID"
	},
	page_body_headerMaxAggregate:{
		id:"ID"
	},
	Page_body_footerDeleteResponse:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		type:"String"
	},
	page_body_footerEdge:{
		node:"page_body_footer",
		cursor:"ConnectionCursor"
	},
	Page_body_footerConnection:{
		pageInfo:"PageInfo",
		edges:"page_body_footerEdge"
	},
	page_body_footerAggregateGroupBy:{
		id:"ID"
	},
	page_body_footerCountAggregate:{
		id:"Int"
	},
	page_body_footerSumAggregate:{
		id:"Float"
	},
	page_body_footerAvgAggregate:{
		id:"Float"
	},
	page_body_footerMinAggregate:{
		id:"ID"
	},
	page_body_footerMaxAggregate:{
		id:"ID"
	},
	MainDeleteResponse:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String"
	},
	mainEdge:{
		node:"main",
		cursor:"ConnectionCursor"
	},
	MainConnection:{
		pageInfo:"PageInfo",
		edges:"mainEdge"
	},
	mainAggregateGroupBy:{
		id:"ID"
	},
	mainCountAggregate:{
		id:"Int"
	},
	mainSumAggregate:{
		id:"Float"
	},
	mainAvgAggregate:{
		id:"Float"
	},
	mainMinAggregate:{
		id:"ID"
	},
	mainMaxAggregate:{
		id:"ID"
	},
	PageBodyNavigationDeleteResponse:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String"
	},
	PageBodyNavigationEdge:{
		node:"PageBodyNavigation",
		cursor:"ConnectionCursor"
	},
	PageBodyNavigationConnection:{
		pageInfo:"PageInfo",
		edges:"PageBodyNavigationEdge"
	},
	PageBodyNavigationAggregateGroupBy:{
		id:"ID"
	},
	PageBodyNavigationCountAggregate:{
		id:"Int"
	},
	PageBodyNavigationSumAggregate:{
		id:"Float"
	},
	PageBodyNavigationAvgAggregate:{
		id:"Float"
	},
	PageBodyNavigationMinAggregate:{
		id:"ID"
	},
	PageBodyNavigationMaxAggregate:{
		id:"ID"
	},
	SidebarDeleteResponse:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		title:"String"
	},
	sidebarEdge:{
		node:"sidebar",
		cursor:"ConnectionCursor"
	},
	SidebarConnection:{
		pageInfo:"PageInfo",
		edges:"sidebarEdge"
	},
	sidebarAggregateGroupBy:{
		id:"ID"
	},
	sidebarCountAggregate:{
		id:"Int"
	},
	sidebarSumAggregate:{
		id:"Float"
	},
	sidebarAvgAggregate:{
		id:"Float"
	},
	sidebarMinAggregate:{
		id:"ID"
	},
	sidebarMaxAggregate:{
		id:"ID"
	},
	CommonADeleteResponse:{
		id:"ID",
		created:"DateTime",
		updated_at:"DateTime",
		href:"String",
		rel:"RelEnum",
		target:"TargetEnum"
	},
	CommonAEdge:{
		node:"CommonA",
		cursor:"ConnectionCursor"
	},
	CommonAConnection:{
		pageInfo:"PageInfo",
		edges:"CommonAEdge"
	},
	CommonAAggregateGroupBy:{
		id:"ID"
	},
	CommonACountAggregate:{
		id:"Int"
	},
	CommonASumAggregate:{
		id:"Float"
	},
	CommonAAvgAggregate:{
		id:"Float"
	},
	CommonAMinAggregate:{
		id:"ID"
	},
	CommonAMaxAggregate:{
		id:"ID"
	},
	Query:{
		users:"User",
		whoAmI:"User",
		page:"page",
		pages:"PageConnection",
		head:"head",
		heads:"HeadConnection",
		meta:"meta",
		metas:"MetaConnection",
		body:"body",
		bodies:"BodyConnection",
		page_body_header:"page_body_header",
		page_body_headers:"Page_body_headerConnection",
		page_body_footer:"page_body_footer",
		page_body_footers:"Page_body_footerConnection",
		main:"main",
		mains:"MainConnection",
		pageBodyNavigation:"PageBodyNavigation",
		pageBodyNavigations:"PageBodyNavigationConnection",
		sidebar:"sidebar",
		sidebars:"SidebarConnection",
		commonA:"CommonA",
		commonAS:"CommonAConnection"
	},
	Mutation:{
		setHeadOnPage:"page",
		setBodyOnPage:"page",
		createOnePage:"page",
		createManyPages:"page",
		updateOnePage:"page",
		updateManyPages:"UpdateManyResponse",
		deleteOnePage:"PageDeleteResponse",
		deleteManyPages:"DeleteManyResponse",
		setMetaOnHead:"head",
		createOneHead:"head",
		createManyHeads:"head",
		updateOneHead:"head",
		updateManyHeads:"UpdateManyResponse",
		deleteOneHead:"HeadDeleteResponse",
		deleteManyHeads:"DeleteManyResponse",
		createOneMeta:"meta",
		createManyMetas:"meta",
		updateOneMeta:"meta",
		updateManyMetas:"UpdateManyResponse",
		deleteOneMeta:"MetaDeleteResponse",
		deleteManyMetas:"DeleteManyResponse",
		setHeaderOnBody:"body",
		setNavigationOnBody:"body",
		setMainOnBody:"body",
		setSidebarOnBody:"body",
		setFooterOnBody:"body",
		createOneBody:"body",
		createManyBodies:"body",
		updateOneBody:"body",
		updateManyBodies:"UpdateManyResponse",
		deleteOneBody:"BodyDeleteResponse",
		deleteManyBodies:"DeleteManyResponse",
		createOnePage_body_header:"page_body_header",
		createManyPage_body_headers:"page_body_header",
		updateOnePage_body_header:"page_body_header",
		updateManyPage_body_headers:"UpdateManyResponse",
		deleteOnePage_body_header:"Page_body_headerDeleteResponse",
		deleteManyPage_body_headers:"DeleteManyResponse",
		createOnePage_body_footer:"page_body_footer",
		createManyPage_body_footers:"page_body_footer",
		updateOnePage_body_footer:"page_body_footer",
		updateManyPage_body_footers:"UpdateManyResponse",
		deleteOnePage_body_footer:"Page_body_footerDeleteResponse",
		deleteManyPage_body_footers:"DeleteManyResponse",
		createOneMain:"main",
		createManyMains:"main",
		updateOneMain:"main",
		updateManyMains:"UpdateManyResponse",
		deleteOneMain:"MainDeleteResponse",
		deleteManyMains:"DeleteManyResponse",
		addItemsToPageBodyNavigation:"PageBodyNavigation",
		setItemsOnPageBodyNavigation:"PageBodyNavigation",
		createOnePageBodyNavigation:"PageBodyNavigation",
		createManyPageBodyNavigations:"PageBodyNavigation",
		updateOnePageBodyNavigation:"PageBodyNavigation",
		updateManyPageBodyNavigations:"UpdateManyResponse",
		deleteOnePageBodyNavigation:"PageBodyNavigationDeleteResponse",
		deleteManyPageBodyNavigations:"DeleteManyResponse",
		createOneSidebar:"sidebar",
		createManySidebars:"sidebar",
		updateOneSidebar:"sidebar",
		updateManySidebars:"UpdateManyResponse",
		deleteOneSidebar:"SidebarDeleteResponse",
		deleteManySidebars:"DeleteManyResponse",
		createOneCommonA:"CommonA",
		createManyCommonAS:"CommonA",
		updateOneCommonA:"CommonA",
		updateManyCommonAS:"UpdateManyResponse",
		deleteOneCommonA:"CommonADeleteResponse",
		deleteManyCommonAS:"DeleteManyResponse"
	}
}