name: CI

on: [push, pull_request]

env:
  node_version: "14.x"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        cp .env.example .env
        docker-compose pull db
        docker-compose build
        docker-compose run --rm web sh -c 'exit 0'
    - name: Lint
      run: docker-compose run --rm web yarn lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        cp .env.example .env
        docker-compose pull db
        docker-compose build
        docker-compose run --rm web sh -c 'exit 0'
        docker-compose up --detach
        docker-compose exec -T db psql -U postgres -c 'create database test;'
    - name: Unit test
      run: docker-compose exec -T web yarn test
    - name: E2E test
      run: docker-compose exec -T web yarn test:e2e
